platform :ios, '9.0'
$node_modules_path = '../../node_modules'

require_relative "#{$node_modules_path}/@react-native-community/cli-platform-ios/native_modules"

target 'GoogleSigninSampleApp' do
  # Pods for GoogleSigninSampleApp
  pod 'GoogleSignIn', '5.0.0'

  pod 'React-cxxreact', :path => "#{$node_modules_path}/react-native/ReactCommon/cxxreact"
  pod 'React-jsi', :path => "#{$node_modules_path}/react-native/ReactCommon/jsi"
  pod 'React-jsiexecutor', :path => "#{$node_modules_path}/react-native/ReactCommon/jsiexecutor"
  pod 'React-jsinspector', :path => "#{$node_modules_path}/react-native/ReactCommon/jsinspector"
  pod 'ReactCommon/jscallinvoker', :path => "#{$node_modules_path}/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "#{$node_modules_path}/react-native/ReactCommon"
  pod 'Yoga', :path => "#{$node_modules_path}/react-native/ReactCommon/yoga"

  pod 'DoubleConversion', :podspec => "#{$node_modules_path}/react-native/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{$node_modules_path}/react-native/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{$node_modules_path}/react-native/third-party-podspecs/Folly.podspec"

  use_native_modules!("../..")
end
